### ISSUE TITLE
Add course material for Cyber Security

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-basil#10]
Add links to journals , video links , pdfs anything which you prefer.

The material should be **FREE** and list should be **ordered** from basics to higher.

You need to link between categories and add the contents in the corresponding pages.

**Comment by georgioupanayiotis** [comment]
Hello @Aniket762 , Can you assign this to me ?

**Comment by Aniket762** [comment]
@georgioupanayiotis go for it

**Comment by georgioupanayiotis** [comment]
@Aniket762 opened PR https://github.com/Webwiznitr/Project-basil/pull/26
