### ISSUE TITLE
Add header 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-basil#2]
Don't add regular bootstrap header add something funky.

Don't forget to add screenshot of the header which you are adding.

**Comment by githubANURAG1** [comment]
Hi, this is my first time in hactoberfest can you please assign it to me.

**Comment by Aniket762** [comment]
@githubANURAG1 sure dude just be quick and make something amazing don't forget to share screenshot

**Comment by kanchitank** [comment]
## I have tried the header section with animations. Please let me know if you like the design. 

![header](https://user-images.githubusercontent.com/65490196/95201870-247a1400-07fe-11eb-95ec-1a1452ec55bb.gif)

**Comment by kanchitank** [comment]
@Aniket762 Should I create a PR?

**Comment by Aniket762** [comment]
Looks great 😍

@kanchitank create the PR

**Comment by kanchitank** [comment]
@Aniket762 Sure Okay! ^_^

**Comment by kanchitank** [comment]
##  @Aniket762 It is responsive as well.

![header_responsive](https://user-images.githubusercontent.com/65490196/95204426-b46d8d00-0801-11eb-8cbb-c651857398c9.gif)

**Comment by Aniket762** [comment]
@kanchitank  Nice 🤩

Please create the pull request

**Comment by kanchitank** [comment]
@Aniket762 Created a pull request!
