### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-basil#3]
Not just regular footer. Think out of the box and add the most creative footer.

Don't forget to add the screenshot of the footer.

**Comment by githubANURAG1** [comment]
Hi, this is my first time in hactoberfest can you please assign it to me.

**Comment by Aniket762** [comment]
@githubANURAG1 sure but be quick and make something create

**Comment by manvendrajpoot** [comment]
I would like to do this.
Is this kind Ok!
Please do let me know.
![footer](https://user-images.githubusercontent.com/53949277/95186364-8bd89980-07e7-11eb-979c-1ff9e1508684.jpg)

**Comment by Aniket762** [comment]
Hey @manvendra264, this looks good but I want something really creative can you show some different layout?

**Comment by manvendrajpoot** [comment]
@Aniket762 as of now I have this only. But as per the project requirement, I can make it. Please specify the requirement of the same.

**Comment by Aniket762** [comment]
### I would prefer to have a vector image at the footer with no quick links just written designed with love . Any vector would work. A fixed image in the footer 
![footer](https://user-images.githubusercontent.com/67703407/95192921-90ee1680-07f0-11eb-8c12-8e6900469fcf.png)

**Comment by manvendrajpoot** [comment]
Sure I can do. Please assign this to me @Aniket762

**Comment by Aniket762** [comment]
@manvendra264 Go for it! 

Add the before and after screenshots

Happy coding 😁

**Comment by kanchitank** [comment]
### @Aniket762 Tried designing the footer. Please let me know if you like it. And should I create a PR? 

![footer](https://user-images.githubusercontent.com/65490196/95215350-82aef300-080e-11eb-82a3-7ba8baa6de30.gif)

### Footer responsiveness

![footer_responsive](https://user-images.githubusercontent.com/65490196/95215357-85114d00-080e-11eb-9e85-9ebc531d8427.gif)

**Comment by Aniket762** [comment]
@kanchitank  Wow 🤩🤩 you are amazing 

Sure create the PR

**Comment by kanchitank** [comment]
@Aniket762 Thank you! ^_^
Yes on it!

**Comment by kanchitank** [comment]
@Aniket762 Created a PR. Hope you like it.
