### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by sumana2001** [Webwiznitr/Project-basil#47]
Fix the footer in all the pages by changing the content and keeping only the required portions

**Comment by ankitzm** [comment]
I will work on this issue.

**Comment by ankitzm** [comment]
#55 Done but haven't changed address as I don't know what will be there exactly.

**Comment by sumana2001** [comment]
Hi thanks for the pr. Please make a few changes:
1. There is a spelling error in the about portion
2. The layout should be made such that there is a contact us, about and links column
3. The contact us contains the social media icons whose links you can get from https://webwiznitr.xyz/
4. Links will contain the links to the various topics

**Comment by ankitzm** [comment]
#56 pr made
topics links can't be added to that as it' not available there, so I have added home, topic and contacts link.
