### ISSUE TITLE
Add course material for ML

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-basil#6]
Add links to journals , video links , pdfs anything which you prefer.

The material should be **FREE** and list should be **ordered** from basics to higher.

You need to link between categories and add the contents in the corresponding pages.

**Comment by aditimaurya** [comment]
Hey, @Aniket762 could you please assign this to me? 
I'll be happy to contribute.

**Comment by aleenajoseph993** [comment]
Hello @Aniket762 Can I contribute too?

**Comment by Aniket762** [comment]
@aditimaurya @aleenajoseph993 I am assigning to both of you be quick and include good resources which are free and list them in correct order. 

Best of luck 😁
