### ISSUE TITLE
Add course material for Web development 

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-basil#8]
Add links to journals , video links , pdfs anything which you prefer.

The material should be **FREE** and list should be **ordered** from basics to higher.

You need to link between categories and add the contents in the corresponding pages.

**Comment by saurabhhere** [comment]
Hi, Can you assign it to me?

**Comment by Aniket762** [comment]
Hey @saurabhhere Go for it  😁

**Comment by saurabhhere** [comment]
@Aniket762 I got stuck with some work so you can assign it to someone else.
I apologize if I have caused you any inconvenience.

**Comment by Aniket762** [comment]
@saurabhhere No issues 

Thanks for informing 😀

**Comment by aayushi2883** [comment]
hey, could i work on this?

**Comment by Aniket762** [comment]
Sure @aayushi2883 go for it 😁

Just share the topics in correct order and include only free resources . For now just submit the data in a text file

**Comment by aleenajoseph993** [comment]
Hey @Aniket762 Can u assign me for this task too?

**Comment by iamrishavraj1** [comment]
Hello Sir,Can You Please Assign me for This task

**Comment by Aniket762** [comment]
@iamrishavraj1 create a PR with a text file in which include links to videos, articles and other resources. Give don't forget to order them
